title: MapsIndoors Documentation
email: support@mapsindoors.com
description: >- # this means to ignore newlines until "baseurl:"
  The documentation site for the MapsIndoors SDKs for iOS, Android and Web, as well as the Integration API and MapsIndoors CMS.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mapsindoors.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

exclude:
  - README.md
  - vendor
  - Gemfile
  - Gemfile.lock
  - package.json
  - node_modules

kramdown:
  # This is needed for the Table of Contents to work in Kramdown
  parse_block_html: true

# This is to ensure the permalinks below are displayed as /slug/, not /slug/index.html (e.g. https://mapsindoors.com/docs/ios/v3/set-up-your-enviroment).
permalink: pretty

collections_dir: collections

collections:
  ios:
    output: true
    permalink: :collection/:path/
  cms:
    output: true
    permalink: :collection/:path/
  android:
    output: true
    permalink: :collection/:path/
  api:
    output: true
    permalink: :collection/:path/
  web:
    output: true
    permalink: :collection/:path/

defaults:
  -
    scope:
      path: "" # targets all files in the collection
    values:
      layout: default
      published: false
  -
    scope:
      path: "_cms"
    values:
      platform: CMS
  -
    scope:
      path: "_ios"
    values:
      platform: iOS
  -
    scope:
      path: "_ios/v2"
    values:
      version: v2
  -
    scope:
      path: "_ios/v2/tutorials"
    values:
      version: v2
      layout: tutorial
  -
    scope:
      path: "_ios/v3"
    values:
      version: v3
      layout: tutorial
  -
    scope:
      path: "_android"
    values:
      platform: Android
  -
    scope:
      path: "_android/v2"
    values:
      version: v2
  -
    scope:
      path: "_android/v2/tutorials"
    values:
      layout: tutorial
  -
    scope:
      path: "_android/v3"
    values:
      version: v3
  -
    scope:
      path: "_android/v3/tutorials"
    values:
      layout: tutorial
  -
    scope:
      path: "_api"
    values:
      platform: API
  -
    scope:
      path: "_api/v1"
    values:
      version: v1
      layout: tutorial
  -
    scope:
      path: "_web"
    values:
      platform: Web
  -
    scope:
      path: "_web/v2"
    values:
      version: v2
  -
    scope:
      path: "_web/v3"
    values:
      version: v3
      layout: tutorial
